# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

module GoogleTests
  module Constants
    # Constants for: Dataset.project
    D_PROJECT_DATA = [
      'test project#0 data',
      'test project#1 data',
      'test project#2 data',
      'test project#3 data',
      'test project#4 data'
    ].freeze

    # Constants for: Dataset.name
    D_NAME_DATA = [
      'test name#0 data',
      'test name#1 data',
      'test name#2 data',
      'test name#3 data',
      'test name#4 data'
    ].freeze

    # Constants for: Table.project
    T_PROJECT_DATA = [
      'test project#0 data',
      'test project#1 data',
      'test project#2 data',
      'test project#3 data',
      'test project#4 data'
    ].freeze

    # Constants for: Table.dataset
    T_DATASET_DATA = [
      'test dataset#0 data',
      'test dataset#1 data',
      'test dataset#2 data',
      'test dataset#3 data',
      'test dataset#4 data'
    ].freeze

    # Constants for: Table.name
    T_NAME_DATA = [
      'test name#0 data',
      'test name#1 data',
      'test name#2 data',
      'test name#3 data',
      'test name#4 data'
    ].freeze
  end
end
