# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

module Google
  module Bigquery
    module Data
      # A class to manage data for TimePartitioning for table.
      class TableTimePartitioning
        include Comparable

        attr_reader :expiration_ms
        attr_reader :type

        def to_json(_arg = nil)
          {
            'expirationMs' => expiration_ms,
            'type' => type
          }.reject { |_k, v| v.nil? }.to_json
        end

        def to_s
          {
            expiration_ms: expiration_ms.to_s,
            type: type.to_s
          }.map { |k, v| "#{k}: #{v}" }.join(', ')
        end

        def ==(other)
          return false unless other.is_a? TableTimePartitioning
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            return false if compare[:self] != compare[:other]
          end
          true
        end

        def <=>(other)
          return false unless other.is_a? TableTimePartitioning
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            result = compare[:self] <=> compare[:other]
            return result unless result.zero?
          end
          0
        end

        def inspect
          to_json
        end

        private

        def compare_fields(other)
          [
            { self: expiration_ms, other: other.expiration_ms },
            { self: type, other: other.type }
          ]
        end
      end

      # Manages a TableTimePartitioning nested object
      # Data is coming from the GCP API
      class TableTimePartitioningApi < TableTimePartitioning
        def initialize(args)
          @expiration_ms = Google::Bigquery::Property::Integer.api_parse(args['expirationMs'])
          @type = Google::Bigquery::Property::Enum.api_parse(args['type'])
        end
      end

      # Manages a TableTimePartitioning nested object
      # Data is coming from the Chef catalog
      class TableTimePartitioningCatalog < TableTimePartitioning
        def initialize(args)
          @expiration_ms = Google::Bigquery::Property::Integer.catalog_parse(args[:expiration_ms])
          @type = Google::Bigquery::Property::Enum.catalog_parse(args[:type])
        end
      end
    end

    module Property
      # A class to manage input to TimePartitioning for table.
      class TableTimePartitioning
        def self.coerce
          ->(x) { ::Google::Bigquery::Property::TableTimePartitioning.catalog_parse(x) }
        end

        # Used for parsing Chef catalog
        def self.catalog_parse(value)
          return if value.nil?
          return value if value.is_a? Data::TableTimePartitioning
          Data::TableTimePartitioningCatalog.new(value)
        end

        # Used for parsing GCP API responses
        def self.api_parse(value)
          return if value.nil?
          return value if value.is_a? Data::TableTimePartitioning
          Data::TableTimePartitioningApi.new(value)
        end
      end
    end
  end
end
