# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

require 'google/bigquery/property/array'
module Google
  module Bigquery
    module Data
      # A class to manage data for UserDefinedFunctionResources for table.
      class TableUserDefinedFunctionResources
        include Comparable

        attr_reader :inline_code
        attr_reader :resource_uri

        def to_json(_arg = nil)
          {
            'inlineCode' => inline_code,
            'resourceUri' => resource_uri
          }.reject { |_k, v| v.nil? }.to_json
        end

        def to_s
          {
            inline_code: inline_code.to_s,
            resource_uri: resource_uri.to_s
          }.map { |k, v| "#{k}: #{v}" }.join(', ')
        end

        def ==(other)
          return false unless other.is_a? TableUserDefinedFunctionResources
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            return false if compare[:self] != compare[:other]
          end
          true
        end

        def <=>(other)
          return false unless other.is_a? TableUserDefinedFunctionResources
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            result = compare[:self] <=> compare[:other]
            return result unless result.zero?
          end
          0
        end

        def inspect
          to_json
        end

        private

        def compare_fields(other)
          [
            { self: inline_code, other: other.inline_code },
            { self: resource_uri, other: other.resource_uri }
          ]
        end
      end

      # Manages a TableUserDefinedFunctionResources nested object
      # Data is coming from the GCP API
      class TableUserDefinedFunctionResourcesApi < TableUserDefinedFunctionResources
        def initialize(args)
          @inline_code = Google::Bigquery::Property::String.api_parse(args['inlineCode'])
          @resource_uri = Google::Bigquery::Property::String.api_parse(args['resourceUri'])
        end
      end

      # Manages a TableUserDefinedFunctionResources nested object
      # Data is coming from the Chef catalog
      class TableUserDefinedFunctionResourcesCatalog < TableUserDefinedFunctionResources
        def initialize(args)
          @inline_code = Google::Bigquery::Property::String.catalog_parse(args[:inline_code])
          @resource_uri = Google::Bigquery::Property::String.catalog_parse(args[:resource_uri])
        end
      end
    end

    module Property
      # A class to manage input to UserDefinedFunctionResources for table.
      class TableUserDefinedFunctionResources
        def self.coerce
          ->(x) { ::Google::Bigquery::Property::TableUserDefinedFunctionResources.catalog_parse(x) }
        end

        # Used for parsing Chef catalog
        def self.catalog_parse(value)
          return if value.nil?
          return value if value.is_a? Data::TableUserDefinedFunctionResources
          Data::TableUserDefinedFunctionResourcesCatalog.new(value)
        end

        # Used for parsing GCP API responses
        def self.api_parse(value)
          return if value.nil?
          return value if value.is_a? Data::TableUserDefinedFunctionResources
          Data::TableUserDefinedFunctionResourcesApi.new(value)
        end
      end

      # A Chef property that holds an integer
      class TableUserDefinedFunctionResourcesArray < Google::Bigquery::Property::Array
        def self.coerce
          lambda do |x|
            ::Google::Bigquery::Property::TableUserDefinedFunctionResourcesArray.catalog_parse(x)
          end
        end

        # Used for parsing Chef catalog
        def self.catalog_parse(value)
          return if value.nil?
          return TableUserDefinedFunctionResources.catalog_parse(value) \
            unless value.is_a?(::Array)
          value.map { |v| TableUserDefinedFunctionResources.catalog_parse(v) }
        end

        # Used for parsing GCP API responses
        def self.api_parse(value)
          return if value.nil?
          return TableUserDefinedFunctionResources.api_parse(value) \
            unless value.is_a?(::Array)
          value.map { |v| TableUserDefinedFunctionResources.api_parse(v) }
        end
      end
    end
  end
end
