# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

module Google
  module Bigquery
    module Data
      # A class to manage data for StreamingBuffer for table.
      class TableStreamingBuffer
        include Comparable

        attr_reader :estimated_bytes
        attr_reader :estimated_rows
        attr_reader :oldest_entry_time

        def to_json(_arg = nil)
          {
            'estimatedBytes' => estimated_bytes,
            'estimatedRows' => estimated_rows,
            'oldestEntryTime' => oldest_entry_time
          }.reject { |_k, v| v.nil? }.to_json
        end

        def to_s
          {
            estimated_bytes: estimated_bytes.to_s,
            estimated_rows: estimated_rows.to_s,
            oldest_entry_time: oldest_entry_time.to_s
          }.map { |k, v| "#{k}: #{v}" }.join(', ')
        end

        def ==(other)
          return false unless other.is_a? TableStreamingBuffer
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            return false if compare[:self] != compare[:other]
          end
          true
        end

        def <=>(other)
          return false unless other.is_a? TableStreamingBuffer
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            result = compare[:self] <=> compare[:other]
            return result unless result.zero?
          end
          0
        end

        def inspect
          to_json
        end

        private

        def compare_fields(other)
          [
            { self: estimated_bytes, other: other.estimated_bytes },
            { self: estimated_rows, other: other.estimated_rows },
            { self: oldest_entry_time, other: other.oldest_entry_time }
          ]
        end
      end

      # Manages a TableStreamingBuffer nested object
      # Data is coming from the GCP API
      class TableStreamingBufferApi < TableStreamingBuffer
        def initialize(args)
          @estimated_bytes = Google::Bigquery::Property::Integer.api_parse(args['estimatedBytes'])
          @estimated_rows = Google::Bigquery::Property::Integer.api_parse(args['estimatedRows'])
          @oldest_entry_time =
            Google::Bigquery::Property::Integer.api_parse(args['oldestEntryTime'])
        end
      end

      # Manages a TableStreamingBuffer nested object
      # Data is coming from the Chef catalog
      class TableStreamingBufferCatalog < TableStreamingBuffer
        def initialize(args)
          @estimated_bytes =
            Google::Bigquery::Property::Integer.catalog_parse(args[:estimated_bytes])
          @estimated_rows = Google::Bigquery::Property::Integer.catalog_parse(args[:estimated_rows])
          @oldest_entry_time =
            Google::Bigquery::Property::Integer.catalog_parse(args[:oldest_entry_time])
        end
      end
    end

    module Property
      # A class to manage input to StreamingBuffer for table.
      class TableStreamingBuffer
        def self.coerce
          ->(x) { ::Google::Bigquery::Property::TableStreamingBuffer.catalog_parse(x) }
        end

        # Used for parsing Chef catalog
        def self.catalog_parse(value)
          return if value.nil?
          return value if value.is_a? Data::TableStreamingBuffer
          Data::TableStreamingBufferCatalog.new(value)
        end

        # Used for parsing GCP API responses
        def self.api_parse(value)
          return if value.nil?
          return value if value.is_a? Data::TableStreamingBuffer
          Data::TableStreamingBufferApi.new(value)
        end
      end
    end
  end
end
